---
- hosts: all
  vars:
    user: "youtux"
  tasks:
    - name: install apt packages
      become: true
      apt:
        update_cache: true
        state: latest
        name:
        - zsh
        - tmux

    - name: Use zsh shell
      become: true
      user:
        name: "{{user}}"
        shell: /usr/bin/zsh

    - name: Check oh-my-zsh
      stat: 
        path: ~/.oh-my-zsh
      register: oh_my_zsh_dir
      
    - name: Install oh-my-zsh
      shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      when: oh_my_zsh_dir.stat.exists == 0

    - name: Update apt packages to the latest version
      become: true
      apt:
        upgrade: full

    - name: remove old apt packages
      become: true
      apt:
        autoremove: true
    
    # - include: tasks/docker.yaml